export const females = [
  {
    name: 'Alex Mcneill',
    gender: 'Female',
    birthDate: new Date('1994-01-01'),
    email: 'alexmcneill@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Charlotte Miller',
    gender: 'Female',
    birthDate: new Date('1993-01-01'),
    email: 'charlottemiller@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Alexandra Gruber',
    gender: 'Female',
    birthDate: new Date('1997-01-01'),
    email: 'alexandragruber@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Naomi Kolski',
    gender: 'Female',
    birthDate: new Date('1989-01-01'),
    email: 'naomikolski@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Gayle Gorringe',
    gender: 'Female',
    birthDate: new Date('1962-01-01'),
    email: 'gaylegorringe@warner.systems',
    division: ['Master'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Chelsea Clarke',
    gender: 'Female',
    birthDate: new Date('2001-01-01'),
    email: 'chelseaclarke@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Brooke Rice',
    gender: 'Female',
    birthDate: new Date('1994-01-01'),
    email: 'brookerice@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Kate Cowen',
    gender: 'Female',
    birthDate: new Date('2002-01-01'),
    email: 'katecowen@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Saskia Robinson',
    gender: 'Female',
    birthDate: new Date('2004-01-01'),
    email: 'saskiarobinson@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Renee Boyd',
    gender: 'Female',
    birthDate: new Date('2003-01-01'),
    email: 'reneeboyd@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Georgia Edmonds',
    gender: 'Female',
    birthDate: new Date('2003-01-01'),
    email: 'georgiaedmonds@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Michaela Carins',
    gender: 'Female',
    birthDate: new Date('2001-01-01'),
    email: 'michaelacarins@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Bella Franklin',
    gender: 'Female',
    birthDate: new Date('2000-01-01'),
    email: 'bellafranklin@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Emily Christieson',
    gender: 'Female',
    birthDate: new Date('1996-01-01'),
    email: 'emilychristieson@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Phoenix Newitt',
    gender: 'Female',
    birthDate: new Date('2006-01-01'),
    email: 'phoenixnewitt@warner.systems',
    division: ['Teen'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Abby Meyer',
    gender: 'Female',
    birthDate: new Date('1998-01-01'), // age 26
    email: 'abbymeyer@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Samm Knowles',
    gender: 'Female',
    birthDate: new Date('2002-01-01'),
    email: 'sammknowles@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Stella Reid',
    gender: 'Female',
    birthDate: new Date('2005-01-01'),
    email: 'stellareid@warner.systems',
    division: ['Teen'],
    events: ['Push Pull'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Danielle Hansson',
    gender: 'Female',
    birthDate: new Date('1990-01-01'),
    email: 'daniellehansson@warner.systems',
    division: ['Open'],
    events: ['Push Pull'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Fiona Elliott',
    gender: 'Female',
    birthDate: new Date('1972-01-01'),
    email: 'fionaelliott@warner.systems',
    division: ['Master'],
    events: ['Push Pull'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Millie Lamprecht',
    gender: 'Female',
    birthDate: new Date('1993-01-01'), // age 31
    email: 'millielamprecht@warner.systems',
    division: ['Open'],
    events: ['Push Pull'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Kathleen James',
    gender: 'Female',
    birthDate: new Date('1991-01-01'),
    email: 'kathleenjames@warner.systems',
    division: ['Open'],
    events: ['Deadlift only'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
]
export const males = [
  {
    name: 'Peter Pike',
    gender: 'Male',
    birthDate: new Date('1988-01-01'),
    email: 'peterpike@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Chris Barker',
    gender: 'Male',
    birthDate: new Date('1986-01-01'),
    email: 'chrisbarker@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Riley Leitch',
    gender: 'Male',
    birthDate: new Date('2003-01-01'),
    email: 'rileyleitch@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Braydon Hall',
    gender: 'Male',
    birthDate: new Date('2002-01-01'),
    email: 'braydonhall@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Anthony Xepapas',
    gender: 'Male',
    birthDate: new Date('1989-01-01'),
    email: 'anthonyxepapas@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Toby Barnett',
    gender: 'Male',
    birthDate: new Date('2001-01-01'),
    email: 'tobybarnett@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '111.9',
    squatOpener: '370',
    squatRackHeight: '15in',
    benchOpener: '190',
    benchRackHeight: '8/1',
    deadliftOpener: '320',
  },
  {
    name: 'Rohan Wheeler',
    gender: 'Male',
    birthDate: new Date('2000-01-01'),
    email: 'rohanwheeler@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Tom Major',
    gender: 'Male',
    birthDate: new Date('1996-01-01'),
    email: 'tommajor@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Christopher Demarte',
    gender: 'Male',
    birthDate: new Date('2004-01-01'),
    email: 'christopherdemarte@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Justin Nobes',
    gender: 'Male',
    birthDate: new Date('1987-01-01'),
    email: 'justinnobes@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Joannah Kafer',
    gender: 'Female',
    birthDate: new Date('1984-01-01'), // age 40
    email: 'joannahkafer@warner.systems',
    division: ['Open'],
    events: ['Squat only'],
    equipment: 'wraps',
    weight: '79.6',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Theo Randall',
    gender: 'Male',
    birthDate: new Date('1997-01-01'), // age 27
    email: 'theorandall@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '88.7',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Themeli Mangos',
    gender: 'Male',
    birthDate: new Date('1994-01-01'),
    email: 'themelimangos@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Lewis Dowling',
    gender: 'Male',
    birthDate: new Date('1993-01-01'),
    email: 'lewisdowling@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Hughie Vollmer',
    gender: 'Male',
    birthDate: new Date('2007-01-01'),
    email: 'hughievollmer@warner.systems',
    division: ['Teen'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Charlie Dufty',
    gender: 'Male',
    birthDate: new Date('2006-01-01'),
    email: 'charliedufty@warner.systems',
    division: ['Teen'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Lorenzo Monsif',
    gender: 'Male',
    birthDate: new Date('1994-01-01'),
    email: 'lorenzomonsif@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Nick Bailey',
    gender: 'Male',
    birthDate: new Date('1975-01-01'),
    email: 'nickbailey@warner.systems',
    division: ['Master'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Sam Dufty',
    gender: 'Male',
    birthDate: new Date('2001-01-01'),
    email: 'samdufty@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Beowulf Hamilton',
    gender: 'Male',
    birthDate: new Date('1996-01-01'),
    email: 'beowulfhamilton@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Ken Hughes',
    gender: 'Male',
    birthDate: new Date('1948-01-01'),
    email: 'kenhughes@warner.systems',
    division: ['Master'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Will Bevis',
    gender: 'Male',
    birthDate: new Date('2008-01-01'),
    email: 'willbevis@warner.systems',
    division: ['Teen'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Tristan Fawdry',
    gender: 'Male',
    birthDate: new Date('2006-01-01'),
    email: 'tristanfawdry@warner.systems',
    division: ['Teen'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Caleb Noble',
    gender: 'Male',
    birthDate: new Date('2003-01-01'),
    email: 'calebnoble@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Jason Ellard',
    gender: 'Male',
    birthDate: new Date('2000-01-01'),
    email: 'jasonellard@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Andrew Murray',
    gender: 'Male',
    birthDate: new Date('1996-01-01'),
    email: 'andrewmurray@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Mitch Dufty',
    gender: 'Male',
    birthDate: new Date('1992-01-01'), // 32
    email: 'mitchdufty@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '93.65',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Michael Thomas',
    gender: 'Male',
    birthDate: new Date('1974-01-01'),
    email: 'michaelthomas@warner.systems',
    division: ['Master'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Jake Quinn',
    gender: 'Male',
    birthDate: new Date('2006-01-01'),
    email: 'jakequinn@warner.systems',
    division: ['Teen'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Brayden Midson-Laredo',
    gender: 'Male',
    birthDate: new Date('2000-01-01'),
    email: 'braydenmidsonlaredo@warner.systems',
    division: ['Open'],
    events: ['Push Pull'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Ben Green',
    gender: 'Male',
    birthDate: new Date('2007-01-01'),
    email: 'bengreen@warner.systems',
    division: ['Teen'],
    events: ['Push Pull'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Callum Austin',
    gender: 'Male',
    birthDate: new Date('2002-01-01'),
    email: 'callumaustin@warner.systems',
    division: ['Open'],
    events: ['Bench only'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Tarkyn Coppleman',
    gender: 'Male',
    birthDate: new Date('2002-01-01'),
    email: 'tarkyncoppleman@warner.systems',
    division: ['Open'],
    events: ['Bench only'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Carl Pearson',
    gender: 'Male',
    birthDate: new Date('1984-01-01'),
    email: 'carlpearson@warner.systems',
    division: ['Master'],
    events: ['Bench only'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Jacob Langford',
    gender: 'Male',
    birthDate: new Date('1986-01-01'),
    email: 'jacoblangford@warner.systems',
    division: ['Open'],
    events: ['Deadlift only'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Oli Ewart',
    gender: 'Male',
    birthDate: new Date('2007-01-01'),
    email: 'oliewart@warner.systems',
    division: ['Teen'],
    events: ['Deadlift only'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Liam Tilley',
    gender: 'Male',
    birthDate: new Date('2005-01-01'),
    email: 'liamtilley@warner.systems',
    division: ['Teen'],
    events: ['Deadlift only'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Deegan Seadon',
    gender: 'Male',
    birthDate: new Date('2001-01-01'),
    email: 'deeganseadon@warner.systems',
    division: ['Open'],
    events: ['Deadlift only'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Damien Ziomek',
    gender: 'Male',
    birthDate: new Date('1985-01-01'),
    email: 'damienziomek@warner.systems',
    division: ['Open'],
    events: ['Deadlift only'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
]

export const atlasUsers = [
  {
    name: 'Alex Mcneill',
    gender: 'Female',
    birthDate: new Date('1994-01-01'),
    email: 'alexmcneill@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Charlotte Miller',
    gender: 'Female',
    birthDate: new Date('1993-01-01'),
    email: 'charlottemiller@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Alexandra Gruber',
    gender: 'Female',
    birthDate: new Date('1997-01-01'),
    email: 'alexandragruber@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '72.5',
    squatOpener: '175',
    squatRackHeight: '19out',
    benchOpener: '90',
    benchRackHeight: '6/0',
    deadliftOpener: '180',
  },
  {
    name: 'Naomi Kolski',
    gender: 'Female',
    birthDate: new Date('1989-01-01'),
    email: 'naomikolski@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Gayle Gorringe',
    gender: 'Female',
    birthDate: new Date('1962-01-01'),
    email: 'gaylegorringe@warner.systems',
    division: ['Master'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Chelsea Clarke',
    gender: 'Female',
    birthDate: new Date('2001-01-01'),
    email: 'chelseaclarke@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Brooke Rice',
    gender: 'Female',
    birthDate: new Date('1994-01-01'),
    email: 'brookrice@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Kate Cowen',
    gender: 'Female',
    birthDate: new Date('2002-01-01'),
    email: 'katecowen@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Saskia Robinson',
    gender: 'Female',
    birthDate: new Date('2004-01-01'),
    email: 'saskiarobinson@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Renee Boyd',
    gender: 'Female',
    birthDate: new Date('2003-01-01'),
    email: 'reneeboyd@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Georgia Edmonds',
    gender: 'Female',
    birthDate: new Date('2003-01-01'),
    email: 'georgiaedmonds@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: '',
    gender: '',
    birthDate: new Date('1994-01-01'),
    email: '',
    division: [''],
    events: ['Squat, Bench, Deadlift'],
    equipment: '',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
]
