export const females = [
  {
    name: 'Alex Mcneill',
    gender: 'Female',
    birthDate: new Date('1994-01-01'),
    email: 'alexmcneill@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '65.6',
    squatOpener: '165',
    squatRackHeight: '23/out',
    benchOpener: '110',
    benchRackHeight: '2/0',
    deadliftOpener: '170',
  },
  {
    name: 'Charlotte Miller',
    gender: 'Female',
    birthDate: new Date('1993-01-01'),
    email: 'charlottemiller@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '66.4',
    squatOpener: '155',
    squatRackHeight: '21out',
    benchOpener: '75',
    benchRackHeight: '3/1',
    deadliftOpener: '155',
  },
  {
    name: 'Alexandra Gruber',
    gender: 'Female',
    birthDate: new Date('1997-01-01'),
    email: 'alexandragruber@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '72.5',
    squatOpener: '175',
    squatRackHeight: '19out',
    benchOpener: '90',
    benchRackHeight: '6/0',
    deadliftOpener: '180',
  },
  {
    name: 'Naomi Kolski',
    gender: 'Female',
    birthDate: new Date('1989-01-01'),
    email: 'naomikolski@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '75.4',
    squatOpener: '125',
    squatRackHeight: '18out',
    benchOpener: '65',
    benchRackHeight: '6/2',
    deadliftOpener: '165',
  },
  {
    name: 'Gayle Gorringe',
    gender: 'Female',
    birthDate: new Date('1962-01-01'),
    email: 'gaylegorringe@warner.systems',
    division: ['Master'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '81.6',
    squatOpener: '130',
    squatRackHeight: '21out',
    benchOpener: '67.5',
    benchRackHeight: '5/0',
    deadliftOpener: '137.5',
  },
  {
    name: 'Chelsea Clarke',
    gender: 'Female',
    birthDate: new Date('2001-01-01'),
    email: 'chelseaclarke@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Brooke Rice',
    gender: 'Female',
    birthDate: new Date('1994-01-01'),
    email: 'brookerice@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Kate Cowen',
    gender: 'Female',
    birthDate: new Date('2002-01-01'),
    email: 'katecowen@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '65',
    squatOpener: '90',
    squatRackHeight: '9out',
    benchOpener: '50',
    benchRackHeight: '6/3',
    deadliftOpener: '110',
  },
  {
    name: 'Saskia Robinson',
    gender: 'Female',
    birthDate: new Date('2004-01-01'),
    email: 'saskiarobinson@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '78.8',
    squatOpener: '110',
    squatRackHeight: '14out',
    benchOpener: '50',
    benchRackHeight: '7/1',
    deadliftOpener: '140',
  },
  {
    name: 'Renee Boyd',
    gender: 'Female',
    birthDate: new Date('2003-01-01'),
    email: 'reneeboyd@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Georgia Edmonds',
    gender: 'Female',
    birthDate: new Date('2003-01-01'),
    email: 'georgiaedmonds@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '89.9',
    squatOpener: '110',
    squatRackHeight: '10out',
    benchOpener: '65',
    benchRackHeight: '6/0',
    deadliftOpener: '120',
  },
  {
    name: 'Michaela Carins',
    gender: 'Female',
    birthDate: new Date('2001-01-01'),
    email: 'michaelacarins@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Bella Franklin',
    gender: 'Female',
    birthDate: new Date('2000-01-01'),
    email: 'bellafranklin@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '85',
    squatOpener: '100',
    squatRackHeight: '15out',
    benchOpener: '60',
    benchRackHeight: '8/0',
    deadliftOpener: '125',
  },
  {
    name: 'Emily Christieson',
    gender: 'Female',
    birthDate: new Date('1996-01-01'),
    email: 'emilychristieson@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Phoenix Newitt',
    gender: 'Female',
    birthDate: new Date('2006-01-01'),
    email: 'phoenixnewitt@warner.systems',
    division: ['Teen'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Abby Meyer',
    gender: 'Female',
    birthDate: new Date('1998-01-01'), // age 26
    email: 'abbymeyer@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '90',
    squatOpener: '125',
    squatRackHeight: '8out',
    benchOpener: '70',
    benchRackHeight: '8/0',
    deadliftOpener: '150',
  },
  {
    name: 'Samm Knowles',
    gender: 'Female',
    birthDate: new Date('2002-01-01'),
    email: 'sammknowles@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '62.2',
    squatOpener: '112.5',
    squatRackHeight: '22out',
    benchOpener: '60',
    benchRackHeight: '4/4',
    deadliftOpener: '130',
  },
  {
    name: 'Stella Reid',
    gender: 'Female',
    birthDate: new Date('2005-01-01'),
    email: 'stellareid@warner.systems',
    division: ['Teen'],
    events: ['Push Pull'],
    equipment: 'sleeves',
    weight: '63.5',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '55',
    benchRackHeight: '7/1',
    deadliftOpener: '130',
  },
  {
    name: 'Danielle Hansson',
    gender: 'Female',
    birthDate: new Date('1990-01-01'),
    email: 'daniellehansson@warner.systems',
    division: ['Open'],
    events: ['Push Pull'],
    equipment: 'sleeves',
    weight: '58.6',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '65',
    benchRackHeight: '3/0',
    deadliftOpener: '107.5',
  },
  {
    name: 'Fiona Elliott',
    gender: 'Female',
    birthDate: new Date('1972-01-01'),
    email: 'fionaelliott@warner.systems',
    division: ['Master'],
    events: ['Push Pull'],
    equipment: 'sleeves',
    weight: '74.5',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '50',
    benchRackHeight: '6/1',
    deadliftOpener: '125',
  },
  {
    name: 'Millie Lamprecht',
    gender: 'Female',
    birthDate: new Date('1993-01-01'), // age 31
    email: 'millielamprecht@warner.systems',
    division: ['Open'],
    events: ['Push Pull'],
    equipment: 'sleeves',
    weight: '80',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '75',
    benchRackHeight: '7/0',
    deadliftOpener: '175',
  },
  {
    name: 'Kathleen James',
    gender: 'Female',
    birthDate: new Date('1991-01-01'),
    email: 'kathleenjames@warner.systems',
    division: ['Open'],
    events: ['Deadlift only'],
    equipment: 'sleeves',
    weight: '66.7',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '140',
  },
]
export const males = [
  {
    name: 'Peter Pike',
    gender: 'Male',
    birthDate: new Date('1988-01-01'),
    email: 'peterpike@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '96.5',
    squatOpener: '300',
    squatRackHeight: '7out',
    benchOpener: '165',
    benchRackHeight: '10/1',
    deadliftOpener: '300',
  },
  {
    name: 'Chris Barker',
    gender: 'Male',
    birthDate: new Date('1986-01-01'),
    email: 'chrisbarker@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '97.8',
    squatOpener: '235',
    squatRackHeight: '16in',
    benchOpener: '140',
    benchRackHeight: '6/0',
    deadliftOpener: '240',
  },
  {
    name: 'Riley Leitch',
    gender: 'Male',
    birthDate: new Date('2003-01-01'),
    email: 'rileyleitch@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '103.5',
    squatOpener: '240',
    squatRackHeight: '10in',
    benchOpener: '160',
    benchRackHeight: '8/6',
    deadliftOpener: '235',
  },
  {
    name: 'Braydon Hall',
    gender: 'Male',
    birthDate: new Date('2002-01-01'),
    email: 'braydonhall@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '107.5',
    squatOpener: '200',
    squatRackHeight: '12in',
    benchOpener: '120',
    benchRackHeight: '9/4',
    deadliftOpener: '200',
  },
  {
    name: 'Toby Barnett',
    gender: 'Male',
    birthDate: new Date('2001-01-01'),
    email: 'tobybarnett@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '111.9',
    squatOpener: '370',
    squatRackHeight: '15in',
    benchOpener: '190',
    benchRackHeight: '8/1',
    deadliftOpener: '320',
  },
  {
    name: 'Rohan Wheeler',
    gender: 'Male',
    birthDate: new Date('2000-01-01'),
    email: 'rohanwheeler@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '122',
    squatOpener: '145',
    squatRackHeight: '8out',
    benchOpener: '82.5',
    benchRackHeight: '9/3',
    deadliftOpener: '167.5',
  },
  {
    name: 'Tom Major',
    gender: 'Male',
    birthDate: new Date('1996-01-01'),
    email: 'tommajor@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '122.5',
    squatOpener: '295',
    squatRackHeight: '5in',
    benchOpener: '175',
    benchRackHeight: '9/0',
    deadliftOpener: '290',
  },
  {
    name: 'Christopher Demarte',
    gender: 'Male',
    birthDate: new Date('2004-01-01'),
    email: 'christopherdemarte@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Justin Nobes',
    gender: 'Male',
    birthDate: new Date('1987-01-01'),
    email: 'justinnobes@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '81.6',
    squatOpener: '165',
    squatRackHeight: '8out',
    benchOpener: '92.5',
    benchRackHeight: '6/1',
    deadliftOpener: '185',
  },
  {
    name: 'Joannah Kafer',
    gender: 'Female',
    birthDate: new Date('1984-01-01'), // age 40
    email: 'joannahkafer@warner.systems',
    division: ['Open'],
    events: ['Squat only'],
    equipment: 'wraps',
    weight: '79.6',
    squatOpener: '80',
    squatRackHeight: '16out',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Theo Randall',
    gender: 'Male',
    birthDate: new Date('1997-01-01'), // age 27
    email: 'theorandall@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '88.7',
    squatOpener: '250',
    squatRackHeight: '17out',
    benchOpener: '140',
    benchRackHeight: '6/0',
    deadliftOpener: '240',
  },
  {
    name: 'Themeli Mangos',
    gender: 'Male',
    birthDate: new Date('1994-01-01'),
    email: 'themelimangos@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Lewis Dowling',
    gender: 'Male',
    birthDate: new Date('1993-01-01'),
    email: 'lewisdowling@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '123',
    squatOpener: '330',
    squatRackHeight: '18in',
    benchOpener: '210',
    benchRackHeight: '8/0',
    deadliftOpener: '305',
  },
  {
    name: 'Hughie Vollmer',
    gender: 'Male',
    birthDate: new Date('2007-01-01'),
    email: 'hughievollmer@warner.systems',
    division: ['Teen'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '94.8',
    squatOpener: '155',
    squatRackHeight: '11out',
    benchOpener: '105',
    benchRackHeight: '10/1',
    deadliftOpener: '205',
  },
  {
    name: 'Charlie Dufty',
    gender: 'Male',
    birthDate: new Date('2006-01-01'),
    email: 'charliedufty@warner.systems',
    division: ['Teen'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '95',
    squatOpener: '180',
    squatRackHeight: '15out',
    benchOpener: '90',
    benchRackHeight: '9/1',
    deadliftOpener: '200',
  },
  {
    name: 'Lorenzo Monsif',
    gender: 'Male',
    birthDate: new Date('1994-01-01'),
    email: 'lorenzomonsif@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '98.5',
    squatOpener: '185',
    squatRackHeight: '8out',
    benchOpener: '95',
    benchRackHeight: '8/5',
    deadliftOpener: '205',
  },
  {
    name: 'Nick Bailey',
    gender: 'Male',
    birthDate: new Date('1975-01-01'),
    email: 'nickbailey@warner.systems',
    division: ['Master'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Sam Dufty',
    gender: 'Male',
    birthDate: new Date('2001-01-01'),
    email: 'samdufty@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '106.7',
    squatOpener: '300',
    squatRackHeight: '14out',
    benchOpener: '150',
    benchRackHeight: '9/1',
    deadliftOpener: '300',
  },
  {
    name: 'Beowulf Hamilton',
    gender: 'Male',
    birthDate: new Date('1996-01-01'),
    email: 'beowulfhamilton@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '99',
    squatOpener: '195',
    squatRackHeight: '6out',
    benchOpener: '135',
    benchRackHeight: '7/1',
    deadliftOpener: '210',
  },
  {
    name: 'Ken Hughes',
    gender: 'Male',
    birthDate: new Date('1948-01-01'),
    email: 'kenhughes@warner.systems',
    division: ['Master'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '120.3',
    squatOpener: '135',
    squatRackHeight: '7in',
    benchOpener: '60',
    benchRackHeight: '10/0',
    deadliftOpener: '180',
  },
  {
    name: 'Will Bevis',
    gender: 'Male',
    birthDate: new Date('2008-01-01'),
    email: 'willbevis@warner.systems',
    division: ['Teen'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Tristan Fawdry',
    gender: 'Male',
    birthDate: new Date('2006-01-01'),
    email: 'tristanfawdry@warner.systems',
    division: ['Teen'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Caleb Noble',
    gender: 'Male',
    birthDate: new Date('2003-01-01'),
    email: 'calebnoble@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '93.4',
    squatOpener: '122.5',
    squatRackHeight: '11in',
    benchOpener: '77.5',
    benchRackHeight: '6/1',
    deadliftOpener: '147.5',
  },
  {
    name: 'Jason Ellard',
    gender: 'Male',
    birthDate: new Date('2000-01-01'),
    email: 'jasonellard@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '88.4',
    squatOpener: '150',
    squatRackHeight: '13out',
    benchOpener: '100',
    benchRackHeight: '10/0',
    deadliftOpener: '250',
  },
  {
    name: 'Andrew Murray',
    gender: 'Male',
    birthDate: new Date('1996-01-01'),
    email: 'andrewmurray@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '88.4',
    squatOpener: '135',
    squatRackHeight: '11out',
    benchOpener: '75',
    benchRackHeight: '9/3',
    deadliftOpener: '185',
  },
  {
    name: 'Mitch Duffy',
    gender: 'Male',
    birthDate: new Date('1992-01-01'), // 32
    email: 'mitchdufty@warner.systems',
    division: ['Open'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '93.65',
    squatOpener: '225',
    squatRackHeight: '8out',
    benchOpener: '150',
    benchRackHeight: '9/1',
    deadliftOpener: '265',
  },
  {
    name: 'Michael Thomas',
    gender: 'Male',
    birthDate: new Date('1974-01-01'),
    email: 'michaelthomas@warner.systems',
    division: ['Master'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'sleeves',
    weight: '89',
    squatOpener: '140',
    squatRackHeight: '13out',
    benchOpener: '100',
    benchRackHeight: '12/0',
    deadliftOpener: '200',
  },
  {
    name: 'Jake Quinn',
    gender: 'Male',
    birthDate: new Date('2006-01-01'),
    email: 'jakequinn@warner.systems',
    division: ['Teen'],
    events: ['Squat, Bench, Deadlift'],
    equipment: 'wraps',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Brayden Midson-Laredo',
    gender: 'Male',
    birthDate: new Date('2000-01-01'),
    email: 'braydenmidsonlaredo@warner.systems',
    division: ['Open'],
    events: ['Push Pull'],
    equipment: 'sleeves',
    weight: '114.6',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '90',
    benchRackHeight: '9/0',
    deadliftOpener: '185',
  },
  {
    name: 'Ben Green',
    gender: 'Male',
    birthDate: new Date('2007-01-01'),
    email: 'bengreen@warner.systems',
    division: ['Teen'],
    events: ['Push Pull'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Callum Austin',
    gender: 'Male',
    birthDate: new Date('2002-01-01'),
    email: 'callumaustin@warner.systems',
    division: ['Open'],
    events: ['Bench only'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Tarkyn Coppleman',
    gender: 'Male',
    birthDate: new Date('2002-01-01'),
    email: 'tarkyncoppleman@warner.systems',
    division: ['Open'],
    events: ['Bench only'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Carl Pearson',
    gender: 'Male',
    birthDate: new Date('1984-01-01'),
    email: 'carlpearson@warner.systems',
    division: ['Master'],
    events: ['Bench only'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Jacob Langford',
    gender: 'Male',
    birthDate: new Date('1986-01-01'),
    email: 'jacoblangford@warner.systems',
    division: ['Open'],
    events: ['Deadlift only'],
    equipment: 'sleeves',
    weight: '106.75',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '270',
  },
  {
    name: 'Oli Ewart',
    gender: 'Male',
    birthDate: new Date('2007-01-01'),
    email: 'oliewart@warner.systems',
    division: ['Teen'],
    events: ['Deadlift only'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Liam Tilley',
    gender: 'Male',
    birthDate: new Date('2005-01-01'),
    email: 'liamtilley@warner.systems',
    division: ['Teen'],
    events: ['Deadlift only'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Deegan Seadon',
    gender: 'Male',
    birthDate: new Date('2001-01-01'),
    email: 'deeganseadon@warner.systems',
    division: ['Open'],
    events: ['Deadlift only'],
    equipment: 'sleeves',
    weight: '',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Damien Ziomek',
    gender: 'Male',
    birthDate: new Date('1985-01-01'),
    email: 'damienziomek@warner.systems',
    division: ['Open'],
    events: ['Deadlift only'],
    equipment: 'sleeves',
    weight: '122.4',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '160',
  },
]

