export const users = [
	{
		email: 'isaac.gillard@gmail.com',
		name: 'isaac gillard',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 100,
		div: 'Open 24-39 yrs',
		age: 32,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'lorenzo.monsif@gmail.com',
		name: 'lorenzo monsif',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 100,
		div: 'Open 24-39 yrs',
		age: 31,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'harrison.pearce@gmail.com',
		name: 'harrison pearce',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 100,
		div: 'Sub-Junior 17-19 yrs',
		age: 18,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'duffy.mitch@gmail.com',
		name: 'mitch duffy',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 100,
		div: 'Open 24-39 yrs',
		age: 29,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'harlee.chauntler@gmail.com',
		name: 'harlee chauntler',
		category: 'open',
		isBench: false,
		isDeadlift: true,
		isSquat: false,
		isPushPull: false,
		is3Lift: false,
		wc: 100,
		div: 'Open 24-39 yrs',
		age: 35,
		sex: 'm',
		equip: 'unequipped',
	},
	{
		email: 'riley.leitch@gmail.com',
		name: 'riley leitch',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 110,
		div: 'Junior 20-23 yrs',
		age: 22,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'sam.bullock@gmail.com',
		name: 'sam bullock',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 110,
		div: 'Masters M1 40-49 yrs',
		age: 45,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'rohan.wheeler@gmail.com',
		name: 'rohan wheeler',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 110,
		div: 'Open 24-39 yrs',
		age: 33,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'anthony.xepapas@gmail.com',
		name: 'anthony xepapas',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 110,
		div: 'Open 24-39 yrs',
		age: 27,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'jake.quinn@gmail.com',
		name: 'jake quinn',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 110,
		div: 'Sub-Junior 17-19 yrs',
		age: 19,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'kayden.weller@gmail.com',
		name: 'kayden weller',
		category: 'open',
		isBench: false,
		isDeadlift: true,
		isSquat: false,
		isPushPull: false,
		is3Lift: false,
		wc: 110,
		div: 'Open 24-39 yrs',
		age: 26,
		sex: 'm',
		equip: 'unequipped',
	},
	{
		email: 'callum.robertson@gmail.com',
		name: 'callum robertson',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 125,
		div: 'Open 24-39 yrs',
		age: 38,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'zeven.andrew@gmail.com',
		name: 'andrew zeven',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 125,
		div: 'Open 24-39 yrs',
		age: 30,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'adam.gordon@gmail.com',
		name: 'adam gordon',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 125,
		div: 'Open 24-39 yrs',
		age: 37,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'joseph.burke@gmail.com',
		name: 'joseph burke',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 125,
		div: 'Junior 20-23 yrs',
		age: 21,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'dj.stubbs@gmail.com',
		name: 'dj stubbs',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 125,
		div: 'Masters M2 50-59 yrs',
		age: 55,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'mattia.moretti@gmail.com',
		name: 'mattia moretti',
		category: 'open',
		isBench: true,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: false,
		wc: 125,
		div: 'Open 24-39 yrs',
		age: 25,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'scott.harvey@gmail.com',
		name: 'scott harvey',
		category: 'open',
		isBench: true,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: false,
		wc: 125,
		div: 'Masters M2 50-59 yrs',
		age: 52,
		sex: 'm',
		equip: 'unequipped',
	},
	{
		email: 'christopher.demarte@gmail.com',
		name: 'christopher demarte',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 67.5,
		div: 'Junior 20-23 yrs',
		age: 23,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'jarrod.demarte@gmail.com',
		name: 'jarrod demarte',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 67.5,
		div: 'Open 24-39 yrs',
		age: 28,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'jordan.grant@gmail.com',
		name: 'jordan grant',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 75,
		div: 'Junior 20-23 yrs',
		age: 20,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'khoi.hoang@gmail.com',
		name: 'khoi hoang',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 75,
		div: 'Open 24-39 yrs',
		age: 34,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'koda.hawkes@gmail.com',
		name: 'koda hawkes',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 75,
		div: 'Teenage 14-16 yrs',
		age: 15,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'gabriel.silva@gmail.com',
		name: 'gabriel silva',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 75,
		div: 'Open 24-39 yrs',
		age: 29,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'jesse.cantrell@gmail.com',
		name: 'jesse cantrell',
		category: 'open',
		isBench: true,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: false,
		wc: 75,
		div: 'Open 24-39 yrs',
		age: 36,
		sex: 'm',
		equip: 'unequipped',
	},
	{
		email: 'mark.gilbert@gmail.com',
		name: 'mark gilbert',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 82.5,
		div: 'Masters M1 40-49 yrs',
		age: 43,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'mitchell.crawford@gmail.com',
		name: 'mitchell crawford',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 82.5,
		div: 'Teenage 14-16 yrs',
		age: 16,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'matthew.ryan@gmail.com',
		name: 'matthew ryan',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: true,
		isPushPull: false,
		is3Lift: false,
		wc: 82.5,
		div: 'Masters M1 40-49 yrs',
		age: 48,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'trent.bassmann@gmail.com',
		name: 'trent bassmann',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 90,
		div: 'Open 24-39 yrs',
		age: 26,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'kayden.randall@gmail.com',
		name: 'kayden randall',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 90,
		div: 'Open 24-39 yrs',
		age: 31,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'theo.randall@gmail.com',
		name: 'theo randall',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 90,
		div: 'Open 24-39 yrs',
		age: 33,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'harry.bartlett@gmail.com',
		name: 'harry bartlett',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 90,
		div: 'Sub-Junior 17-19 yrs',
		age: 17,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'james.coburn@gmail.com',
		name: 'james coburn',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 82.5,
		div: 'Sub-Junior 17-19 yrs',
		age: 18,
		sex: 'm',
		equip: 'classic',
	},
	{
		email: 'connor.haley@gmail.com',
		name: 'connor haley',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 90,
		div: 'Junior 20-23 yrs',
		age: 22,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'jason.ellard@gmail.com',
		name: 'jason ellard',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 90,
		div: 'Open 24-39 yrs',
		age: 39,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'andrew.facciol@gmail.com',
		name: 'andrew facciol',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 90,
		div: 'Open 24-39 yrs',
		age: 27,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'jack.phillips@gmail.com',
		name: 'jack phillips',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 90,
		div: 'Sub-Junior 17-19 yrs',
		age: 19,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'tristan.fawdry@gmail.com',
		name: 'tristan fawdry',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 90,
		div: 'Sub-Junior 17-19 yrs',
		age: 17,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'byunggook.park@gmail.com',
		name: 'byungook park',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 90,
		div: 'Open 24-39 yrs',
		age: 30,
		sex: 'm',
		equip: 'raw',
	},
	{
		email: 'kylie.brown@gmail.com',
		name: 'kylie brown',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 56,
		div: 'Open 24-39 yrs',
		age: 28,
		sex: 'f',
		equip: 'raw',
	},
	{
		email: 'grace-violet.izzard@gmail.com',
		name: 'grace-violet izzard',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 60,
		div: 'Sub-Junior 17-19 yrs',
		age: 18,
		sex: 'f',
		equip: 'raw',
	},
	{
		email: 'abby.donnelly@gmail.com',
		name: 'abby donnelly',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 60,
		div: 'Open 24-39 yrs',
		age: 31,
		sex: 'f',
		equip: 'raw',
	},
	{
		email: 'michelina.weatherall@gmail.com',
		name: 'michelina weatherall',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: true,
		is3Lift: false,
		wc: 60,
		div: 'Masters M1 40-49 yrs',
		age: 44,
		sex: 'f',
		equip: 'unequipped',
	},
	{
		email: 'brooke.rice@gmail.com',
		name: 'brooke rice',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: true,
		is3Lift: false,
		wc: 60,
		div: 'Open 24-39 yrs',
		age: 33,
		sex: 'f',
		equip: 'unequipped',
	},
	{
		email: 'toni.perkins@gmail.com',
		name: 'toni perkins',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 67.5,
		div: 'Open 24-39 yrs',
		age: 29,
		sex: 'f',
		equip: 'classic',
	},
	{
		email: 'stella.reid@gmail.com',
		name: 'stella reid',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 67.5,
		div: 'Junior 20-23 yrs',
		age: 21,
		sex: 'f',
		equip: 'classic',
	},
	{
		email: 'emily.hazzlewood@gmail.com',
		name: 'emily hazzlewood',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 67.5,
		div: 'Open 24-39 yrs',
		age: 27,
		sex: 'f',
		equip: 'raw',
	},
	{
		email: 'georgia.kuys@gmail.com',
		name: 'georgia kuys',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 67.5,
		div: 'Teenage 14-16 yrs',
		age: 15,
		sex: 'f',
		equip: 'raw',
	},
	{
		email: 'ebony-jane.brown@gmail.com',
		name: 'ebony-jane brown',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 67.5,
		div: 'Open 24-39 yrs',
		age: 35,
		sex: 'f',
		equip: 'unequipped',
	},
	{
		email: 'bronwyn.bates@gmail.com',
		name: 'bronwyn bates',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 75,
		div: 'Open 24-39 yrs',
		age: 38,
		sex: 'f',
		equip: 'classic',
	},
	{
		email: 'kahlia.smith@gmail.com',
		name: 'kahlia smith',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 75,
		div: 'Open 24-39 yrs',
		age: 26,
		sex: 'f',
		equip: 'raw',
	},
	{
		email: 'loren.gunn@gmail.com',
		name: 'loren gunn',
		category: 'open',
		isBench: false,
		isDeadlift: true,
		isSquat: false,
		isPushPull: false,
		is3Lift: false,
		wc: 75,
		div: 'Open 24-39 yrs',
		age: 30,
		sex: 'f',
		equip: 'unequipped',
	},
	{
		email: 'holly.miller@gmail.com',
		name: 'holly miller',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: true,
		is3Lift: false,
		wc: 75,
		div: 'Sub-Junior 17-19 yrs',
		age: 19,
		sex: 'f',
		equip: 'unequipped',
	},
	{
		email: 'rosie.reed@gmail.com',
		name: 'rosie reed',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 82.5,
		div: 'Sub-Junior 17-19 yrs',
		age: 18,
		sex: 'f',
		equip: 'raw',
	},
	{
		email: 'emily.christieson@gmail.com',
		name: 'emily christieson',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: true,
		is3Lift: false,
		wc: 82.5,
		div: 'Open 24-39 yrs',
		age: 29,
		sex: 'f',
		equip: 'unequipped',
	},
	{
		email: 'alison.dann@gmail.com',
		name: 'alison dann',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 90,
		div: 'Masters M2 50-59 yrs',
		age: 54,
		sex: 'f',
		equip: 'raw',
	},
	{
		email: 'bella.franklin@gmail.com',
		name: 'bella franklin',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 90,
		div: 'Open 24-39 yrs',
		age: 25,
		sex: 'f',
		equip: 'raw',
	},
	{
		email: 'catherine.moylan@gmail.com',
		name: 'catherine moylan',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 90,
		div: 'Masters M1 40-49 yrs',
		age: 47,
		sex: 'f',
		equip: 'raw',
	},
	{
		email: 'abby.neep@gmail.com',
		name: 'abby neep',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 'SHW',
		div: 'Open 24-39 yrs',
		age: 32,
		sex: 'f',
		equip: 'classic',
	},
	{
		email: 'ari.powell@gmail.com',
		name: 'ari powell',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 'SHW',
		div: 'Masters M1 40-49 yrs',
		age: 41,
		sex: 'f',
		equip: 'raw',
	},
	{
		email: 'phoenix.newitt@gmail.com',
		name: 'phoenix newitt',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 'SHW',
		div: 'Sub-Junior 17-19 yrs',
		age: 17,
		sex: 'f',
		equip: 'raw',
	},
	{
		email: 'alison.butterworth@gmail.com',
		name: 'alison butterworth',
		category: 'open',
		isBench: false,
		isDeadlift: true,
		isSquat: false,
		isPushPull: false,
		is3Lift: false,
		wc: 'SHW',
		div: 'Masters M2 50-59 yrs',
		age: 58,
		sex: 'f',
		equip: 'unequipped',
	},
	{
		email: 'gina.oliver@gmail.com',
		name: 'gina oliver',
		category: 'open',
		isBench: false,
		isDeadlift: false,
		isSquat: false,
		isPushPull: false,
		is3Lift: true,
		wc: 'SHW',
		div: 'Open 24-39 yrs',
		age: 39,
		sex: 'f',
		equip: 'raw',
	},
]
