export const users = [
  {
    email: 'alexmcneill93@gmail.com',
    name: 'alex mcneill',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 67.5,
    div: 'open',
    age: 31,
    sex: 'f',
    equip: 'classic',
  },
  {
    email: 'mitchlee021@gmail.com',
    name: 'mitch lee',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 67.5,
    div: 'open',
    age: 31,
    sex: 'm',
    equip: 'classic',
  },
  {
    email: 'akcornish2@gmail.com',
    name: 'alisha cornish',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: false,
    wc: 90,
    div: 'open',
    age: 38,
    sex: 'f',
    equip: 'raw',
  },
  {
    email: 'andrewfacciol@gmail.com',
    name: 'andrew facciol',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 90,
    div: 'open',
    age: 28,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'amurray1411@gmail.com',
    name: 'andrew murray',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 90,
    div: 'open',
    age: 28,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'anna.down3@gmail.com',
    name: 'anna down',
    category: 'open',
    isBench: true,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: false,
    wc: 60,
    div: 'open',
    age: 25,
    sex: 'f',
    equip: 'raw',
  },
  {
    email: 'anthea2025@gmail.com',
    name: 'anthea collier',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: false,
    wc: 75,
    div: '60+',
    age: 62,
    sex: 'f',
    equip: 'equipped',
  },
  {
    email: 'anthonyx@harpersbathroom.com.au',
    name: 'anthony xepapas',
    category: 'open',
    isBench: true,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: false,
    wc: 110,
    div: 'open',
    age: 35,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'benjakegreen@yahoo.com',
    name: 'ben green',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 75,
    div: '17-19yrs',
    age: 18,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'blakefoster504@yahoo.com',
    name: 'blake foster',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 82.5,
    div: '20-23yrs',
    age: 21,
    sex: 'm',
    equip: 'equipped',
  },
  {
    email: 'ghostyy2188@gmail.com',
    name: 'brodie sinclair',
    category: 'first',
    isBench: true,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: false,
    wc: 67.5,
    div: '14-16yrs',
    age: 16,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'brooke.hodges1234@gmail.com',
    name: 'brooke hodges',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 56,
    div: 'open',
    age: 30,
    sex: 'f',
    equip: 'raw',
  },
  {
    email: 'crmoylan77@gmail.com',
    name: 'catherine moylan',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 90,
    div: '40-49yrs',
    age: 47,
    sex: 'f',
    equip: 'raw',
  },
  {
    email: 'chloemason525@gmail.com',
    name: 'chloe mason',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 90,
    div: 'open',
    age: 26,
    sex: 'f',
    equip: 'raw',
  },
  {
    email: 'chloeamazing11@gmail.com',
    name: 'chloe millwood',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: false,
    wc: 56,
    div: '14-16yrs',
    age: 14,
    sex: 'f',
    equip: 'raw',
  },
  {
    email: 'c.t.whittaker@hotmail.com',
    name: 'chris whittaker',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 100,
    div: 'open',
    age: 34,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'damien.ziomek@gmail.com',
    name: 'damian ziomek',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 125,
    div: '40-49yrs',
    age: 40,
    sex: 'm',
    equip: 'classic',
  },
  {
    email: 'suteerawanit.darwin@gmail.com',
    name: 'darwin suteerawanit',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 100,
    div: 'open',
    age: 29,
    sex: 'm',
    equip: 'classic',
  },
  {
    email: 'declandullaghan@gmail.com',
    name: 'declan dullaghan',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 67.5,
    div: '17-19yrs',
    age: 18,
    sex: 'm',
    equip: 'classic',
  },
  {
    email: 'ebonyjanebrown@outlook.com',
    name: 'ebony-jane brown',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 67.5,
    div: 'open',
    age: 31,
    sex: 'f',
    equip: 'raw',
  },
  {
    email: 'emily.christieson@gmail.com',
    name: 'emily christieson',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: false,
    wc: 90,
    div: 'open',
    age: 27,
    sex: 'f',
    equip: 'raw',
  },
  {
    email: 'finnreed50@gmail.com',
    name: 'finn reed',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 82.5,
    div: '14-16yrs',
    age: 15,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'fionaintas@gmail.com',
    name: 'fiona elliott',
    category: 'novice',
    isBench: false,
    isDeadlift: true,
    isPushPull: false,
    is3Lift: false,
    wc: 82.5,
    div: '50-59yrs',
    age: 52,
    sex: 'f',
    equip: 'raw',
  },
  {
    email: 'ggorringe@zoho.com',
    name: 'gayle gorringe',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 82.5,
    div: '60-69yrs',
    age: 63,
    sex: 'f',
    equip: 'classic',
  },
  {
    email: 'tarakuys@hotmail.com',
    name: 'georgia kuys',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 67.5,
    div: '14-16yrs',
    age: 15,
    sex: 'f',
    equip: 'equipped',
  },
  {
    email: 'pearceharrison94@gmail.com',
    name: 'harrison pearce',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 110,
    div: '14-16yrs',
    age: 16,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'harrybartlett103@yahoo.com.au',
    name: 'harry bartlett',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 90,
    div: '17-19yrs',
    age: 19,
    sex: 'm',
    equip: 'classic',
  },
  {
    email: 'jack3d.sawyer@gmail.com',
    name: 'jack sawyer',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 100,
    div: 'open',
    age: 24,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'Jarrodhalsall32@gmail.com',
    name: 'jarrod halsall',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 82.5,
    div: 'open',
    age: 36,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'joseph.c.burke.2002@gmail.com',
    name: 'joseph burke',
    category: 'open',
    isBench: false,
    isDeadlift: true,
    isPushPull: false,
    is3Lift: false,
    wc: 125,
    div: '20-23yrs',
    age: 22,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'muzza542@gmail.com',
    name: 'joshua murray',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 140,
    div: 'open',
    age: 31,
    sex: 'm',
    equip: 'classic',
  },
  {
    email: 'kelsieogden3@gmail.com',
    name: 'kelsie ogden',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 75,
    div: '20-23yrs',
    age: 21,
    sex: 'f',
    equip: 'raw',
  },
  {
    email: 'lachlan.duhig@gmail.com',
    name: 'lachlan duhig',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 140,
    div: 'open',
    age: 27,
    sex: 'm',
    equip: 'classic',
  },
  {
    email: 'llj_o_dea@hotmail.com',
    name: "leo o'dea",
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: false,
    wc: 75,
    div: '60-69yrs',
    age: 64,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'lewis.dowling@fastlabourhire.com.au',
    name: 'lewis dowling',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 125,
    div: 'open',
    age: 32,
    sex: 'm',
    equip: 'classic',
  },
  {
    email: 'finch_ee@yahoo.com.au',
    name: 'linda finch',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 56,
    div: '40-49yrs',
    age: 49,
    sex: 'f',
    equip: 'classic',
  },
  {
    email: 'cbukuya@yahoo.com.au',
    name: 'lucas moylan',
    category: 'novice',
    isBench: false,
    isDeadlift: true,
    isPushPull: false,
    is3Lift: false,
    wc: 56,
    div: '14-16yrs',
    age: 12,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'luke.howardr33@gmail.com',
    name: 'luke howard',
    category: 'open',
    isBench: false,
    isDeadlift: true,
    isPushPull: false,
    is3Lift: false,
    wc: 90,
    div: 'open',
    age: 38,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'lhantke@gmail.com',
    name: 'lydia hantke',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 90,
    div: '40-49yrs',
    age: 47,
    sex: 'f',
    equip: 'classic',
  },
  {
    email: 'michaelthomas5@bigpond.com',
    name: 'michael thomas',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 90,
    div: '50-59yrs',
    age: 51,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'michaelacarins@hotmail.com',
    name: 'michaela carins',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 75,
    div: '20-23yrs',
    age: 23,
    sex: 'f',
    equip: 'raw',
  },
  {
    email: 'mitch.crawford@icloud.com',
    name: 'mitchell crawford',
    category: 'first',
    isBench: false,
    isDeadlift: true,
    isPushPull: false,
    is3Lift: false,
    wc: 75,
    div: '14-16yrs',
    age: 15,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'ntf1976@icloud.com',
    name: 'nathan foss',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 110,
    div: '40-49yrs',
    age: 49,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'nathanrhodes76@yahoo.com',
    name: 'nathan rhodes',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 100,
    div: '40-49yrs',
    age: 49,
    sex: 'm',
    equip: 'classic',
  },
  {
    email: 'olivierewart@gmail.com',
    name: 'olivier ewart',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: false,
    wc: 75,
    div: '17-19yrs',
    age: 18,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'leeinv66@hotmail.com',
    name: 'peter lee',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 110,
    div: '60-69yrs',
    age: 64,
    sex: 'm',
    equip: 'classic',
  },
  {
    email: 'phoenixdawn2006@icloud.com',
    name: 'phoenix newitt',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 90,
    div: '17-19yrs',
    age: 19,
    sex: 'f',
    equip: 'raw',
  },
  {
    email: 'rosiereed2008@gmail.com',
    name: 'rosie reed',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 82.5,
    div: '17-19yrs',
    age: 17,
    sex: 'f',
    equip: 'raw',
  },
  {
    email: 'sez89@icloud.com',
    name: 'sarah butler',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 67.5,
    div: 'open',
    age: 36,
    sex: 'f',
    equip: 'classic',
  },
  {
    email: 'suepatmore62@gmail.com',
    name: 'sue patmore',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 90,
    div: '60-69yrs',
    age: 62,
    sex: 'f',
    equip: 'classic',
  },
  {
    email: 'taylahlehman1996@gmail.com',
    name: 'taylah lehman',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 67.5,
    div: 'open',
    age: 28,
    sex: 'f',
    equip: 'classic',
  },
  {
    email: 'veronicajww@gmail.com',
    name: 'veronica whish-wilson',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 52,
    div: '50-59yrs',
    age: 50,
    sex: 'f',
    equip: 'raw',
  },
  {
    email: 'willbevis13@gmail.com',
    name: 'will bevis',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: false,
    wc: 67.5,
    div: '14-16yrs',
    age: 16,
    sex: 'm',
    equip: 'raw',
  },
  {
    email: 'seadonzac@gmail.com',
    name: 'zac seadon',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 100,
    div: '20-23yrs',
    age: 22,
    sex: 'm',
    equip: 'classic',
  },
]
