export const users = [
  {
    name: 'alex mcneill',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 67.5,
    div: 'open',
    age: 31,
    sex: 'f',
    equip: 'classic',
  },
  {
    name: 'alisha cornish',
    category: 'novice',
    isBench: false,
    isDeadlift: true,
    isPushPull: false,
    is3Lift: true,
    wc: 90,
    div: 'open',
    age: 38,
    sex: 'f',
    equip: 'raw',
  },
  {
    name: 'andrew facciol',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 90,
    div: 'open',
    age: 28,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'andrew murray',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 90,
    div: 'open',
    age: 28,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'anna down',
    category: 'open',
    isBench: true,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 60,
    div: 'open',
    age: 25,
    sex: 'f',
    equip: 'raw',
  },
  {
    name: 'anthea collier',
    category: 'first',
    isBench: false,
    isDeadlift: true,
    isPushPull: false,
    is3Lift: true,
    wc: 75,
    div: '60+',
    age: 62,
    sex: 'f',
    equip: 'equipped',
  },
  {
    name: 'anthony xepapas',
    category: 'open',
    isBench: true,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 110,
    div: 'open',
    age: 35,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'ben green',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 75,
    div: '17-19yrs',
    age: 18,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'blake foster',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 82.5,
    div: '20-23yrs',
    age: 21,
    sex: 'm',
    equip: 'equipped',
  },
  {
    name: 'brodie sinclair',
    category: 'first',
    isBench: true,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 67.5,
    div: '14-16yrs',
    age: 16,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'brooke hodges',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 56,
    div: 'open',
    age: 30,
    sex: 'f',
    equip: 'raw',
  },
  {
    name: 'catherine moylan',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 90,
    div: '40-49yrs',
    age: 47,
    sex: 'f',
    equip: 'raw',
  },
  {
    name: 'chloe mason',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 90,
    div: 'open',
    age: 26,
    sex: 'f',
    equip: 'raw',
  },
  {
    name: 'chloe millwood',
    category: 'first',
    isBench: false,
    isDeadlift: true,
    isPushPull: false,
    is3Lift: true,
    wc: 56,
    div: '14-16yrs',
    age: 14,
    sex: 'f',
    equip: 'raw',
  },
  {
    name: 'chris whittaker',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 100,
    div: 'open',
    age: 34,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'damian ziomek',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 125,
    div: '40-49yrs',
    age: 40,
    sex: 'm',
    equip: 'classic',
  },
  {
    name: 'darwin suteerawanit',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 100,
    div: 'open',
    age: 29,
    sex: 'm',
    equip: 'classic',
  },
  {
    name: 'declan dullaghan',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 67.5,
    div: '17-19yrs',
    age: 18,
    sex: 'm',
    equip: 'classic',
  },
  {
    name: 'ebony-jane brown',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 67.5,
    div: 'open',
    age: 31,
    sex: 'f',
    equip: 'raw',
  },
  {
    name: 'emily christieson',
    category: 'novice',
    isBench: false,
    isDeadlift: true,
    isPushPull: false,
    is3Lift: true,
    wc: 90,
    div: 'open',
    age: 27,
    sex: 'f',
    equip: 'raw',
  },
  {
    name: 'finn reed',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 82.5,
    div: '14-16yrs',
    age: 15,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'fiona elliott',
    category: 'novice',
    isBench: true,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 82.5,
    div: '50-59yrs',
    age: 52,
    sex: 'f',
    equip: 'raw',
  },
  {
    name: 'gayle gorringe',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 82.5,
    div: '60-69yrs',
    age: 63,
    sex: 'f',
    equip: 'classic',
  },
  {
    name: 'georgia kuys',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 67.5,
    div: '14-16yrs',
    age: 15,
    sex: 'f',
    equip: 'equipped',
  },
  {
    name: 'harrison pearce',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 110,
    div: '14-16yrs',
    age: 16,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'harry bartlett',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 90,
    div: '17-19yrs',
    age: 19,
    sex: 'm',
    equip: 'classic',
  },
  {
    name: 'jack sawyer',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 100,
    div: 'open',
    age: 24,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'jarrod halsall',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 82.5,
    div: 'open',
    age: 36,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'joseph burke',
    category: 'open',
    isBench: true,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 125,
    div: '20-23yrs',
    age: 22,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'joshua murray',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 140,
    div: 'open',
    age: 31,
    sex: 'm',
    equip: 'classic',
  },
  {
    name: 'kelsie ogden',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 75,
    div: '20-23yrs',
    age: 21,
    sex: 'f',
    equip: 'raw',
  },
  {
    name: 'lachlan duhig',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 140,
    div: 'open',
    age: 27,
    sex: 'm',
    equip: 'classic',
  },
  {
    name: "leo o'dea",
    category: 'open',
    isBench: true,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 75,
    div: '60-69yrs',
    age: 64,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'lewis dowling',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 125,
    div: 'open',
    age: 32,
    sex: 'm',
    equip: 'classic',
  },
  {
    name: 'linda finch',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 56,
    div: '40-49yrs',
    age: 49,
    sex: 'f',
    equip: 'classic',
  },
  {
    name: 'lucas moylan',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 56,
    div: '14-16yrs',
    age: 12,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'luke howard',
    category: 'open',
    isBench: true,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 90,
    div: 'open',
    age: 38,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'lydia hantke',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 90,
    div: '40-49yrs',
    age: 47,
    sex: 'f',
    equip: 'classic',
  },
  {
    name: 'michael thomas',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 90,
    div: '50-59yrs',
    age: 51,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'michaela carins',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 75,
    div: '20-23yrs',
    age: 23,
    sex: 'f',
    equip: 'raw',
  },
  {
    name: 'michaela carins',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: false,
    is3Lift: true,
    wc: 75,
    div: '20-23yrs',
    age: 23,
    sex: 'f',
    equip: 'raw',
  },
  {
    name: 'mitchell crawford',
    category: 'first',
    isBench: true,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: false,
    wc: 75,
    div: '14-16yrs',
    age: 15,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'nathan foss',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 110,
    div: '40-49yrs',
    age: 49,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'nathan rhodes',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 100,
    div: '40-49yrs',
    age: 49,
    sex: 'm',
    equip: 'classic',
  },
  {
    name: 'olivier ewart',
    category: 'first',
    isBench: false,
    isDeadlift: true,
    isPushPull: true,
    is3Lift: false,
    wc: 75,
    div: '17-19yrs',
    age: 18,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'peter lee',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 110,
    div: '60-69yrs',
    age: 64,
    sex: 'm',
    equip: 'classic',
  },
  {
    name: 'phoenix newitt',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 90,
    div: '17-19yrs',
    age: 19,
    sex: 'f',
    equip: 'raw',
  },
  {
    name: 'rosie reed',
    category: 'novice',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 82.5,
    div: '17-19yrs',
    age: 17,
    sex: 'f',
    equip: 'raw',
  },
  {
    name: 'sarah butler',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 67.5,
    div: 'open',
    age: 36,
    sex: 'f',
    equip: 'classic',
  },
  {
    name: 'sue patmore',
    category: 'open',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 90,
    div: '60-69yrs',
    age: 62,
    sex: 'f',
    equip: 'classic',
  },
  {
    name: 'taylah lehman',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 67.5,
    div: 'open',
    age: 28,
    sex: 'f',
    equip: 'classic',
  },
  {
    name: 'veronica whish-wilson',
    category: 'first',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 52,
    div: '50-59yrs',
    age: 50,
    sex: 'f',
    equip: 'raw',
  },
  {
    name: 'will bevis',
    category: 'novice',
    isBench: false,
    isDeadlift: true,
    isPushPull: true,
    is3Lift: false,
    wc: 67.5,
    div: '14-16yrs',
    age: 16,
    sex: 'm',
    equip: 'raw',
  },
  {
    name: 'zac seadon',
    category: 'pro',
    isBench: false,
    isDeadlift: false,
    isPushPull: true,
    is3Lift: true,
    wc: 100,
    div: '20-23yrs',
    age: 22,
    sex: 'm',
    equip: 'classic',
  },
]
