import { z } from 'zod'

export const ageDivisionsData: Array<{
  name: string
  minAge: number | string
  maxAge: number | string
  info: string
}> = [
  { name: 'Open', minAge: '', maxAge: '', info: 'Open' },
  { name: 'Teen', minAge: 13, maxAge: 19, info: 'Teen' },
  { name: 'Master', minAge: 50, maxAge: '', info: 'Masters' },
  {
    name: 'First Timers',
    minAge: '',
    maxAge: '',
    info: 'First powerlifting event',
  },
  {
    name: 'Novice',
    minAge: '',
    maxAge: '',
    info: 'Second powerlifting event',
  },
  {
    name: 'TeamBattle',
    minAge: '',
    maxAge: '',
    info: 'Team Battle',
  },
]

export const teams = ['Team 1', 'Team 2', 'Team 3', 'Team 4']

export const eventsData = [
  'Squat, Bench, Deadlift',
  'Squat only',
  'Bench only',
  'Deadlift only',
  'Push Pull',
  'Squat, Bench',
  'Squat, Deadlift',
  'Team Battle',
]

export const equipmentData = [
  'Classic',
  'Raw',
  'Bare',
  'Sleeves',
  'Wraps',
  'Single Ply',
  'Multi Ply',
  'Unlimited',
]

export const wcMData = [52, 56, 60, 67.5, 75, 82.5, 90, 100, 110, 125, 140]

export const wcFData = [
  44, 48, 52, 56, 60, 67.5, 75, 82.5, 90, 100, 110, 125, 140,
]

export const winnerFormular = ['Total', 'Dots', 'Wilks']

export const ceUsers = [
  {
    name: 'Gayle Gorringe',
    gender: 'Female',
    birthDate: new Date('1962-01-01'),
    email: 'ggorringe@zoho.com',
    team: 'MGMs',
    teamLift: 'squat',
    division: ['Open', 'TeamBattle', 'Master'],
    events: ['Squat, Bench, Deadlift'],
    weight: '80.4',
    squatOpener: '105',
    squatRackHeight: '3out',
    benchOpener: '65',
    benchRackHeight: '4',
    deadliftOpener: '135',
  },
  {
    name: 'Jake Quinn',
    gender: 'Male',
    birthDate: new Date('2006-01-01'),
    email: 'jakequinn982@gmail.com',
    team: 'Definitely 6 Foot',
    teamLift: 'squat',
    division: ['Open', 'TeamBattle', 'Novice'],
    events: ['Squat only'],
    weight: '90',
    squatOpener: '185',
    squatRackHeight: '6out',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '185',
  },
  {
    name: 'Brayden Pascoe',
    gender: 'Male',
    birthDate: new Date('1998-01-01'),
    email: 'brayden.pascoe@outlook.com',
    team: 'Iron Titans',
    teamLift: 'squat',
    division: ['Open', 'TeamBattle', 'First Timers'],
    events: ['Squat, Bench, Deadlift'],
    weight: '81.9',
    squatOpener: '150',
    squatRackHeight: '6out',
    benchOpener: '90',
    benchRackHeight: '9',
    deadliftOpener: '185',
  },
  {
    name: 'Toby Barnett',
    gender: 'Male',
    birthDate: new Date('2001-01-01'),
    email: 'tobybarnett01@hotmail.com',
    team: 'CE Heavy Hitters',
    teamLift: 'squat',
    division: ['Open', 'TeamBattle'],
    events: ['Squat only'],
    weight: '109.9',
    squatOpener: '315',
    squatRackHeight: '8in',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Will Bevis',
    gender: 'Male',
    birthDate: new Date('2008-01-01'),
    email: 'willbevis13@gmail.com',
    team: 'Next Gen',
    teamLift: 'squat',
    division: ['Open', 'TeamBattle', 'Teen'],
    events: ['Squat only', 'Bench only'],
    weight: '62.7',
    squatOpener: '130',
    squatRackHeight: '3out',
    benchOpener: '87.5',
    benchRackHeight: '7',
    deadliftOpener: '',
  },
  {
    name: 'Lily Hollister',
    gender: 'Female',
    birthDate: new Date('2008-01-01'),
    email: 'lilyhollister@icloud.com',
    team: 'YEAH THE GIRLS',
    teamLift: 'squat',
    division: ['Open', 'TeamBattle', 'Teen'],
    events: ['Squat only'],
    weight: '87.5',
    squatOpener: '115',
    squatRackHeight: '5out',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Clinton Dean',
    gender: 'Male',
    birthDate: new Date('1973-01-01'),
    email: 'clintondean73@gmail.com',
    team: 'Whiskey Pigness',
    teamLift: 'squat',
    division: ['Open', 'TeamBattle', 'Master'],
    events: ['Squat only'],
    weight: '81',
    squatOpener: '150',
    squatRackHeight: '9out',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Stella Reid',
    gender: 'Female',
    birthDate: new Date('2005-01-01'),
    email: 'stellaxxreid@gmail.com',
    team: 'YEAH THE GIRLS',
    teamLift: 'bench',
    division: ['Open', 'TeamBattle'],
    events: ['Bench only'],
    weight: '65',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '60',
    benchRackHeight: '6',
    deadliftOpener: '',
  },
  {
    name: 'Mitch Lee',
    gender: 'Male',
    birthDate: new Date('1990-01-01'),
    email: 'mitch@comp-edge.com.au',
    team: 'Whiskey Pigness',
    teamLift: 'bench',
    division: ['Open', 'TeamBattle'],
    events: ['Bench only'],
    weight: '117.8',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '200',
    benchRackHeight: '6',
    deadliftOpener: '',
  },
  {
    name: 'Mary Dash',
    gender: 'Female',
    birthDate: new Date('1949-01-01'),
    email: 'maddoggdash@outlook.com',
    team: 'MGMs',
    teamLift: 'bench',
    division: ['Open', 'TeamBattle', 'Master'],
    events: ['Bench only'],
    weight: '60.6',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '40',
    benchRackHeight: '5',
    deadliftOpener: '',
  },
  {
    name: 'Byunggook Park',
    gender: 'Male',
    birthDate: new Date('1998-01-01'),
    email: 'bgpark0330@gmail.com',
    team: 'Iron Titans',
    teamLift: 'bench',
    division: ['Open', 'TeamBattle'],
    events: ['Bench only'],
    weight: '85.4',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '135',
    benchRackHeight: '4',
    deadliftOpener: '',
  },
  {
    name: 'Blake Foster',
    gender: 'Male',
    birthDate: new Date('2004-01-01'),
    email: 'blakefoster504@yahoo.com',
    team: 'Definitely 6 Foot',
    teamLift: 'bench',
    division: ['Open', 'TeamBattle', 'Novice'],
    events: ['Bench only'],
    weight: '76.3',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '107.5',
    benchRackHeight: '4',
    deadliftOpener: '',
  },
  {
    name: 'Joshua Murray',
    gender: 'Male',
    birthDate: new Date('1993-01-01'),
    email: 'muzza542@gmail.com',
    team: 'CE Heavy Hitters',
    teamLift: 'bench',
    division: ['Open', 'TeamBattle'],
    events: ['Bench only'],
    weight: '144.9',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '180',
    benchRackHeight: '9',
    deadliftOpener: '',
  },
  {
    name: 'Zac Seadon',
    gender: 'Male',
    birthDate: new Date('2003-01-01'),
    email: 'seadonzac@gmail.com',
    team: 'Next Gen',
    teamLift: 'deadlift',
    division: ['Open', 'TeamBattle'],
    events: ['Deadlift only'],
    weight: '99.3',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '275',
  },
  {
    name: 'Jamie Dash',
    gender: 'Male',
    birthDate: new Date('1989-01-01'),
    email: 'jamie@comp-edge.com.au',
    team: 'Whiskey Pigness',
    teamLift: 'deadlift',
    division: ['Open', 'TeamBattle'],
    events: ['Deadlift only'],
    weight: '103',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '250',
  },
  {
    name: 'Jarrod Murray',
    gender: 'Male',
    birthDate: new Date('2003-01-01'),
    email: 'jarrod@gmail.com',
    team: 'YEAH THE GIRLS',
    teamLift: 'deadlift',
    division: ['Open', 'TeamBattle'],
    events: ['Deadlift only'],
    weight: '107.6',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '230',
  },
  {
    name: 'Sam Dufty',
    gender: 'Male',
    birthDate: new Date('2002-01-01'),
    email: 'samdufty2014@gmail.com',
    team: 'CE Heavy Hitters',
    teamLift: 'deadlift',
    division: ['Open', 'TeamBattle'],
    events: ['Deadlift only'],
    weight: '107',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '290',
  },
  {
    name: 'Michaela Thomas',
    gender: 'Male',
    birthDate: new Date('1974-01-01'),
    email: 'michaelthomas5@bigpond.com',
    team: 'MGMs',
    teamLift: 'deadlift',
    division: ['Open', 'TeamBattle', 'Master', 'Novice'],
    events: ['Squat, Bench, Deadlift'],
    weight: '89.8',
    squatOpener: '130',
    squatRackHeight: '9out',
    benchOpener: '97.5',
    benchRackHeight: '12',
    deadliftOpener: '200',
  },
  {
    name: 'Andrew Murray',
    gender: 'Male',
    birthDate: new Date('1996-01-01'),
    email: 'amurray1411@gmail.com',
    team: 'Iron Titans',
    teamLift: 'deadlift',
    division: ['Open', 'TeamBattle', 'First Timers'],
    events: ['Squat, Bench, Deadlift'],
    weight: '81',
    squatOpener: '115',
    squatRackHeight: '9out',
    benchOpener: '70',
    benchRackHeight: '9',
    deadliftOpener: '160',
  },
  {
    name: 'Tristan Fawdry',
    gender: 'Male',
    birthDate: new Date('2006-01-01'),
    email: 'tristanfawdry@gmail.com',
    team: 'Definitely 6 Foot',
    teamLift: 'deadlift',
    division: ['Open', 'TeamBattle', 'First Timers'],
    events: ['Deadlift only'],
    weight: '86',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '225',
  },
  {
    name: 'Kelsie Ogden',
    gender: 'Female',
    birthDate: new Date('2003-01-01'),
    email: 'kelsieogden3@gmail.com',
    team: '',
    teamLift: '',
    division: ['Open', 'First Timers'],
    events: ['Squat, Bench, Deadlift'],
    weight: '76.8',
    squatOpener: '95',
    squatRackHeight: '11out',
    benchOpener: '47.5',
    benchRackHeight: '6',
    deadliftOpener: '107.5',
  },
  {
    name: 'Krysten Templar',
    gender: 'Female',
    birthDate: new Date('1995-01-01'),
    email: 'krysten.templar94@outlook.com',
    team: '',
    teamLift: '',
    division: ['Open', 'First Timers'],
    events: ['Squat, Bench, Deadlift'],
    weight: '93.6',
    squatOpener: '50',
    squatRackHeight: '7out',
    benchOpener: '50',
    benchRackHeight: '6',
    deadliftOpener: '50',
  },
  {
    name: 'DJ Stubbs',
    gender: 'Male',
    birthDate: new Date('1967-01-01'),
    email: 'dj@djstubbs.com.au',
    team: '',
    teamLift: '',
    division: ['Open', 'First Timers', 'Master'],
    events: ['Squat, Bench, Deadlift'],
    weight: '118.6',
    squatOpener: '150',
    squatRackHeight: '10out',
    benchOpener: '125',
    benchRackHeight: '7',
    deadliftOpener: '170',
  },
  {
    name: 'Alexandra Purdon',
    gender: 'Female',
    birthDate: new Date('1992-01-01'),
    email: 'alexandra_purdon@outlook.com',
    team: '',
    teamLift: '',
    division: ['Open', 'First Timers'],
    events: ['Squat, Bench, Deadlift'],
    weight: '107.4',
    squatOpener: '80',
    squatRackHeight: '8out',
    benchOpener: '45',
    benchRackHeight: '8',
    deadliftOpener: '130',
  },
  {
    name: 'Brooke Rice',
    gender: 'Female',
    birthDate: new Date('1995-01-01'),
    email: 'brooke.hodges1234@gmail.com',
    team: '',
    teamLift: '',
    division: ['Open', 'First Timers'],
    events: ['Squat, Bench, Deadlift'],
    weight: '54.8',
    squatOpener: '60',
    squatRackHeight: '1out',
    benchOpener: '32.5',
    benchRackHeight: '4',
    deadliftOpener: '75',
  },
  {
    name: 'Caleb Noble',
    gender: 'Male',
    birthDate: new Date('2003-01-01'),
    email: 'calebnoble989@gmail.com',
    team: '',
    teamLift: '',
    division: ['Open', 'First Timers'],
    events: ['Squat, Bench, Deadlift'],
    weight: '92.7',
    squatOpener: '122.5',
    squatRackHeight: '5out',
    benchOpener: '75',
    benchRackHeight: '6',
    deadliftOpener: '130',
  },
  {
    name: 'Rosie Reed',
    gender: 'Female',
    birthDate: new Date('2008-01-01'),
    email: 'RosieReed2008@gmail.com',
    team: '',
    teamLift: '',
    division: ['Open', 'First Timers', 'Teen'],
    events: ['Squat, Bench, Deadlift'],
    weight: '92',
    squatOpener: '90',
    squatRackHeight: '3out',
    benchOpener: '45',
    benchRackHeight: '6',
    deadliftOpener: '120',
  },
  {
    name: 'Andrew Facciol',
    gender: 'Male',
    birthDate: new Date('1996-01-01'),
    email: 'andrewfacciol@gmail.com',
    team: '',
    teamLift: '',
    division: ['Open', 'Novice'],
    events: ['Squat, Bench, Deadlift'],
    weight: '89.9',
    squatOpener: '185',
    squatRackHeight: '8out',
    benchOpener: '117.5',
    benchRackHeight: '8',
    deadliftOpener: '215',
  },
  {
    name: 'Michaela Carins',
    gender: 'Female',
    birthDate: new Date('2001-01-01'),
    email: 'michaelacarins@hotmail.com',
    team: '',
    teamLift: '',
    division: ['Open', 'First Timers'],
    events: ['Squat, Bench, Deadlift'],
    weight: '85.8',
    squatOpener: '110',
    squatRackHeight: '7in',
    benchOpener: '50',
    benchRackHeight: '5',
    deadliftOpener: '120',
  },
  {
    name: 'Georgia Kitic',
    gender: 'Female',
    birthDate: new Date('2001-01-01'),
    email: 'kiticgeorgia@gmail.com',
    team: '',
    teamLift: '',
    division: ['Open', 'Novice'],
    events: ['Squat, Bench, Deadlift'],
    weight: '65.4',
    squatOpener: '105',
    squatRackHeight: '2out',
    benchOpener: '60',
    benchRackHeight: '3',
    deadliftOpener: '130',
  },
  {
    name: 'Damien Taylor',
    gender: 'Male',
    birthDate: new Date('1982-01-01'),
    email: 'damot8@hotmail.com',
    team: '',
    teamLift: '',
    division: ['Open', 'First Timers'],
    events: ['Squat, Bench, Deadlift'],
    weight: '107.2',
    squatOpener: '120',
    squatRackHeight: '8out',
    benchOpener: '90',
    benchRackHeight: '7',
    deadliftOpener: '160',
  },
  {
    name: 'Yabby Midson',
    gender: 'Female',
    birthDate: new Date('1997-01-01'),
    email: 'yeabby@hotmail.com',
    team: '',
    teamLift: '',
    division: ['Open', 'First Timers'],
    events: ['Squat only'],
    weight: '65',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Mathew McKay',
    gender: 'Male',
    birthDate: new Date('1992-01-01'),
    email: 'memckay2000@gmail.com',
    team: 'Next Gen',
    teamLift: 'bench',
    division: ['Open'],
    events: ['Bench only'],
    weight: '102.5',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '195',
    benchRackHeight: '6/5',
    deadliftOpener: '',
  },
  {
    name: 'Jake Von Stieglitz',
    gender: 'Male',
    birthDate: new Date('2007-01-01'),
    email: 'jakevs111@icloud.com',
    team: '',
    teamLift: '',
    division: ['Open', 'Novice', 'Teen'],
    events: ['Bench only'],
    weight: '104',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Alisha Cornish',
    gender: 'Female',
    birthDate: new Date('1987-01-01'),
    email: 'akcornish2@gmail.com',
    team: '',
    teamLift: '',
    division: ['Open', 'First Timers'],
    events: ['Bench only', 'Deadlift only'],
    weight: '85.5',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '50',
    benchRackHeight: '8',
    deadliftOpener: '120',
  },
  {
    name: 'Lucas Moylan',
    gender: 'Male',
    birthDate: new Date('2013-01-01'),
    email: 'crmoylan77@gmail.com',
    team: '',
    teamLift: '',
    division: ['Open', 'First Timers', 'Teen'],
    events: ['Deadlift only'],
    weight: '55.9',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '60',
  },
  {
    name: 'Troy Moylan',
    gender: 'Male',
    birthDate: new Date('1977-01-01'),
    email: 'crmoylan77@gmail.com',
    team: '',
    teamLift: '',
    division: ['Open', 'First Timers'],
    events: ['Deadlift only'],
    weight: '115.4',
    squatOpener: '105',
    squatRackHeight: '12out',
    benchOpener: '82.5',
    benchRackHeight: '8',
    deadliftOpener: '100',
  },
  {
    name: 'Luke Smith',
    gender: 'Male',
    birthDate: new Date('1985-01-01'),
    email: 'luke.d.smith85@gmail.com',
    team: '',
    teamLift: '',
    division: ['Open'],
    events: ['Deadlift only'],
    weight: '125',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
  {
    name: 'Harlee Chauntler',
    gender: 'Male',
    birthDate: new Date('1994-01-01'),
    email: 'hchauntler@gmail.com',
    team: '',
    teamLift: '',
    division: ['Open'],
    events: ['Deadlift only'],
    weight: '101.8',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '210',
  },
  {
    name: 'Oscar Davie',
    gender: 'Male',
    birthDate: new Date('2001-01-01'),
    email: 'oscardavie@hotmail.com',
    team: '',
    teamLift: '',
    division: ['Open'],
    events: ['Deadlift only'],
    weight: '110',
    squatOpener: '',
    squatRackHeight: '',
    benchOpener: '',
    benchRackHeight: '',
    deadliftOpener: '',
  },
]
