import type { Config } from 'tailwindcss'

const config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  safelist: [
    'scale-10',
    'scale-15',
    'scale-20',
    'scale-25',
    'scale-30',
    'scale-35',
    'scale-40',
    'scale-45',
    'scale-50',
    'scale-55',
    'scale-60',
    'scale-65',
    'scale-70',
    'scale-75',
    'scale-80',
    'scale-85',
    'scale-90',
    'scale-95',
    'scale-100',
    'scale-105',
    'scale-110',
    'scale-115',
    'scale-120',
    'scale-125',
    'scale-130',
    'scale-135',
    'scale-140',
    'scale-145',
    'scale-150',
    'scale-155',
    'scale-160',
    'scale-165',
    'scale-170',
    'scale-175',
    'scale-180',
    'scale-185',
    'scale-190',
    'scale-195',
    'scale-200',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      gridTemplateColumns: {
        '11': 'repeat(11, minmax(0, 1fr))',
        '15': 'repeat(15, minmax(0, 1fr))',
        '14': 'repeat(14, minmax(0, 1fr))',
        '17': 'repeat(17, minmax(0, 1fr))',
      },
      scale: {
        '10': '.1',
        '15': '.15',
        '20': '.2',
        '25': '.25',
        '30': '.3',
        '35': '.35',
        '40': '.4',
        '45': '.45',
        '50': '.5',
        '55': '.55',
        '60': '.6',
        '65': '.65',
        '70': '.7',
        '75': '.75',
        '80': '.8',
        '85': '.85',
        '90': '.9',
        '95': '.95',
        '100': '1',
        '105': '1.05',
        '110': '1.1',
        '115': '1.15',
        '120': '1.2',
        '125': '1.25',
        '130': '1.3',
        '135': '1.35',
        '140': '1.4',
        '145': '1.45',
        '150': '1.5',
        '155': '1.55',
        '160': '1.6',
        '165': '1.65',
        '170': '1.7',
        '175': '1.75',
        '180': '1.8',
        '185': '1.85',
        '190': '1.9',
        '195': '1.95',
        '200': '2',
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        complete: {
          DEFAULT: 'hsl(var(--complete))',
          foreground: 'hsl(var(--complete-foreground))',
        },
        warning: {
          DEFAULT: 'hsl(var(--warning))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'caret-blink': {
          '0%,70%,100%': { opacity: '1' },
          '20%,50%': { opacity: '0' },
        },
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'caret-blink': 'caret-blink 1.25s ease-out infinite',
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config

export default config
