ALTER TABLE `pb_comp_day_info` ADD `result_div` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `result_gender` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `result_wc` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `result_age` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen1` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen1_size` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen2` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen2_size` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen3` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen3_size` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen4` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen4_size` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen5` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen5_size` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen6` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen6_size` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen7` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen7_size` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen8` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen8_size` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen9` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen9_size` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen10` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen10_size` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen11` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen11_size` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen12` text;--> statement-breakpoint
ALTER TABLE `pb_comp_day_info` ADD `screen12_size` text;